import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = process.cwd();
const appRoot = join(root, "src", "app");

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => entry.isDirectory() ? walk(join(dir, entry.name)) : [join(dir, entry.name)]);
}

function routeFor(file: string): string {
  const parts = relative(appRoot, file).split(sep).slice(0, -1).filter((part) => !/^\(.+\)$/.test(part));
  return "/" + parts.join("/");
}

const pageFiles = walk(appRoot).filter((file) => file.endsWith(`${sep}page.tsx`)).sort();
const apiFiles = walk(join(appRoot, "api")).filter((file) => file.endsWith(`${sep}route.ts`)).sort();

const pageRows = pageFiles.map((file) => {
  const source = readFileSync(file, "utf8");
  const route = routeFor(file) || "/";
  const apiDeps = [...source.matchAll(/fetch\([`'"]([^`'"]+)/g)].map((match) => match[1]).filter((value) => value.startsWith("/api/"));
  const db = /prisma\./.test(source);
  const staticUi = /const\s+(POLICIES|RULES|DATA_MODELS|backups)\s*=\s*\[/.test(source);
  const role = route.startsWith("/admin") ? "Management" : route.startsWith("/api-keys") ? "SUPERADMIN" : ["/check-in", "/history", "/leave", "/payslip", "/chat", "/sos"].includes(route) ? "EMPLOYEE" : "Public/Auth";
  const status = staticUi ? "UI_ONLY" : apiDeps.length || db ? "PARTIAL" : "UNVERIFIED";
  return `| ${route} | ${relative(root, file).replaceAll("\\", "/")} | ${role} | ${apiDeps.join("<br>") || "—"} | ${db ? "YES" : "NO/INDIRECT"} | ${status} |`;
});

const apiRows = apiFiles.map((file) => {
  const source = readFileSync(file, "utf8");
  const route = routeFor(file);
  const methods = [...source.matchAll(/export async function (GET|POST|PUT|PATCH|DELETE)/g)].map((match) => match[1]).join(", ") || "UNKNOWN";
  const auth = /requireRole/.test(source) ? "RBAC" : /validateApiKeyRequest/.test(source) ? "API_KEY" : /requireSession|getSessionFromRequest/.test(source) ? "AUTH" : "NONE";
  const db = /prisma\./.test(source) ? "YES" : "NO/INDIRECT";
  const audit = /auditLog|auditService|AuditService/.test(source) ? "YES" : "NO";
  return `| ${route} | ${methods} | ${auth} | ${db} | ${audit} | ${auth === "NONE" && route !== "/api/ping" && !route.startsWith("/api/auth/") ? "REVIEW" : "PARTIAL"} |`;
});

const document = `# Route Inventory\n\nGenerated by static inspection on 2026-09-28. “PARTIAL” does not mean the workflow was browser-tested; it means a concrete dependency was found.\n\n## Pages (${pageRows.length})\n\n| Route | Page | Role boundary | API dependency | Direct DB dependency | Status |\n|---|---|---|---|---|---|\n${pageRows.join("\n")}\n\n## APIs (${apiRows.length})\n\n| Route | Methods | Authentication | Database | Audit | Status |\n|---|---|---|---|---|---|\n${apiRows.join("\n")}\n`;

writeFileSync(join(root, "docs", "ROUTE_INVENTORY.md"), document, "utf8");
console.log(`Wrote ${pageRows.length} pages and ${apiRows.length} APIs.`);
