"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, XCircle, MapPin } from "lucide-react";
import { showError, showSuccess } from "@/lib/swal";

interface Item { id: string; type: string; timestamp: string; distance: number; note: string | null; employee: { code: string; firstName: string; lastName: string; position: string; site: { name: string } } }
export default function AdminAttendancePage() {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const response = await fetch("/api/admin/attendance?status=pending", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setItems(body.attendances || []); } catch (error) { showError("โหลดข้อมูลไม่สำเร็จ", error instanceof Error ? error.message : "เกิดข้อผิดพลาด"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const decide = async (ids: string[], action: "APPROVE" | "REJECT") => { const response = await fetch("/api/admin/attendance", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids, action }) }); const body = await response.json(); if (!response.ok) return showError("บันทึกไม่สำเร็จ", body.error); showSuccess("บันทึกแล้ว", action === "APPROVE" ? "อนุมัติรายการแล้ว" : "ปฏิเสธรายการแล้ว"); await load(); };
  return <div className="space-y-4 max-w-5xl mx-auto"><div className="p-5 rounded-2xl bg-surface-bg border border-surface-border flex justify-between"><div><h1 className="text-2xl font-bold">อนุมัติการลงเวลา</h1><p className="text-sm text-content-muted">รายการจริงที่อยู่นอก Geofence หรือรอตรวจสอบ</p></div><button disabled={!items.length} onClick={() => decide(items.map((item) => item.id), "APPROVE")} className="px-4 rounded-xl bg-brand-600 text-white disabled:opacity-50">อนุมัติทั้งหมด</button></div>
    {loading ? <div className="p-8 text-center">กำลังโหลด...</div> : !items.length ? <div className="p-8 text-center bg-surface-bg rounded-2xl border border-surface-border">ไม่มีรายการรออนุมัติ</div> : <div className="space-y-3">{items.map((item) => <div key={item.id} className="p-4 rounded-2xl bg-surface-bg border border-surface-border flex justify-between gap-4"><div><div className="font-bold">{item.employee.code} · {item.employee.firstName} {item.employee.lastName}</div><div className="text-sm">{item.type} · {new Date(item.timestamp).toLocaleString("th-TH", { timeZone: "Asia/Bangkok" })}</div><div className="text-xs text-content-muted flex items-center"><MapPin className="w-3 h-3 mr-1" />{item.employee.site.name} · {Math.round(item.distance)} เมตร</div>{item.note && <div className="text-xs mt-1">{item.note}</div>}</div><div className="flex gap-2"><button onClick={() => decide([item.id], "APPROVE")} className="p-2 text-emerald-600"><CheckCircle2 /></button><button onClick={() => decide([item.id], "REJECT")} className="p-2 text-red-600"><XCircle /></button></div></div>)}</div>}
  </div>;
}
